### PR TITLE
Basic IPv6 support

### PR DESCRIPTION
**Pull request by Connoropolous**
@neonphog 

This is a start... but I am seeing this after it runs for about 60 seconds:
```
{ type: 'conError',
  id: 'wss:out:2.vvxxtlg9m5',
  error: 'Error: connect ETIMEDOUT fc55:d888:da0b:94bb:427::1:55443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)' }
```
---

@lucksus: "After intensive debugging I'm convinced that this PR contains everything needed to support IPv6 addresses and that the `conError` posted above by @Connoropolous is a different issue, likely related to ZeroTier. I suggest we merge this branch now and then build node-disconnection code in another PR since this is a different story."

### CODE REVIEW

**Comment by neonphog** [comment]
(*$&(*&@P(* - ... we might have to disable the ipv6 test on travis, apparently there is no support https://github.com/travis-ci/travis-ci/issues/8891

**Comment by lucksus** [comment]
@Connoropolous and I have been playing with zerotier and tried connecting first standalone n3h instances, which seemed to work without error once we used the right address to bind to, and then conductors running holochain-basic-chat spawning n3h. The connection seemed to work for a few seconds, our three nodes (I had two) exchanged peers and we could also see log outputs of entries being gossiped and held. But then quickly the connection broke up. 

Saw the following errors. First, when Connor connected to my node:
```
2019-04-11 19:09:10:holo-chat: debug/scheduled_jobs: tick
TIMEOUT gossiping with peer HcSCjS58rU9f75hPxhANfiniugzbem4fw3MRCKp3Axj9wz34VE77jMAm5iD78sr
TIMEOUT gossiping with peer HcScj4UbwgANpn4b4gsE987qi5GH4tg3qqHqdJSSTwdztkpz5YOiIeNO96kbe6a
TIMEOUT gossiping with peer HcSCjS58rU9f75hPxhANfiniugzbem4fw3MRCKp3Axj9wz34VE77jMAm5iD78sr
2019-04-11 19:09:20:holo-chat: debug/scheduled_jobs: tick
TIMEOUT gossiping with peer HcScj4UbwgANpn4b4gsE987qi5GH4tg3qqHqdJSSTwdztkpz5YOiIeNO96kbe6a
TIMEOUT gossiping with peer HcSCjS58rU9f75hPxhANfiniugzbem4fw3MRCKp3Axj9wz34VE77jMAm5iD78sr
[Object: null prototype] {
  type: 'conError',
  id: 'wss:out:2s.liglqcsw2',
  error:
   'Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:167:27)' }
TIMEOUT gossiping with peer HcScj4UbwgANpn4b4gsE987qi5GH4tg3qqHqdJSSTwdztkpz5YOiIeNO96kbe6a
2019-04-11 19:09:30:holo-chat: debug/scheduled_jobs: tick
TIMEOUT gossiping with peer HcSCiZhpTG9dhog9ow9OA4Z9yjAarsnj3oiU5ZSbcff4pbrfBVC6wVsCi8kjeci
TIMEOUT gossiping with peer HcSCjS58rU9f75hPxhANfiniugzbem4fw3MRCKp3Axj9wz34VE77jMAm5iD78sr
TIMEOUT gossiping with peer HcScj4UbwgANpn4b4gsE987qi5GH4tg3qqHqdJSSTwdztkpz5YOiIeNO96kbe6a
2019-04-11 19:09:40:holo-chat: debug/scheduled_jobs: tick
```

**Comment by lucksus** [comment]
Then later, when I connected with my mac to my workstation:
```
2019-04-11 19:12:30:holo-chat: debug/scheduled_jobs: tick
TIMEOUT gossiping with peer HcSCiZhpTG9dhog9ow9OA4Z9yjAarsnj3oiU5ZSbcff4pbrfBVC6wVsCi8kjeci
TIMEOUT gossiping with peer HcSCitMk46xdzpzna9wfzdKs3dNtiwbf4hUzRGQ3WScbq9bbn3epZTYm43Wzqba
2019-04-11 19:12:34:holo-chat: debug/net/handle: ignoring, same id
2019-04-11 19:12:34:holo-chat: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p"), target: HashString("QmRknp74VCAAgZxub3HNLzvAs4orVjMje4LMzRZWHXyhDq"), tag: "public_stream" }
2019-04-11 19:12:34:holo-chat: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("QmRknp74VCAAgZxub3HNLzvAs4orVjMje4LMzRZWHXyhDq"), target: HashString("HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi"), tag: "has_member" }
2019-04-11 19:12:34:holo-chat: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi"), target: HashString("QmRknp74VCAAgZxub3HNLzvAs4orVjMje4LMzRZWHXyhDq"), tag: "member_of" }
2019-04-11 19:12:34:holo-chat: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi"), target: HashString("QmQ2pmbtAB5ff5p8kf4FZtCdt6e3xJpXJ4an8DZAcrEP4b"), tag: "profile" }
2019-04-11 19:12:34:holo-chat: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("Qmeb26KAiWwoG29VsCARZibdUwchfBD8D771QkJRB41Nxd"), target: HashString("HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi"), tag: "member_tag" }
2019-04-11 19:12:34:holo-chat: debug/net/handle: HandleStoreEntry: EntryData { dna_address: HashString("QmU7qS2SReM31SfdBuyaGhFCy9mABuenTD3M2TXbiujzFE"), provider_agent_id: "HcScIf7MJejaj887bsEA7GOyWWzq3f9diFXGZOcTPigz8irvWCmNUd6eE34f64i", entry_address: HashString("HcScIf7MJejaj887bsEA7GOyWWzq3f9diFXGZOcTPigz8irvWCmNUd6eE34f64i"), entry_content: Object({"entry": Object({"AgentId": Object({"nick": String("HoloTester1"), "pub_sign_key": String("HcScIf7MJejaj887bsEA7GOyWWzq3f9diFXGZOcTPigz8irvWCmNUd6eE34f64i")})}), "header": Object({"entry_type": String("AgentId"), "entry_address": String("HcScIf7MJejaj887bsEA7GOyWWzq3f9diFXGZOcTPigz8irvWCmNUd6eE34f64i"), "provenances": Array([Array([String("HcScIf7MJejaj887bsEA7GOyWWzq3f9diFXGZOcTPigz8irvWCmNUd6eE34f64i"), String("BM1VBfBa7me46W99Tj7Yn+lhLCJAHk8fVH7pTiQrJgPWdNJvGD8xI1No+MFTtSf5HXEuEO3yKjeSSpWGWlkZCg==")])]), "link": String("QmVQKcjC7NKgEAnbCuCdpXxZfuni5FaSvbRkqKfGGUNPTM"), "link_same_type": Null, "link_update_delete": Null, "timestamp": String("2019-04-11T17:12:30+00:00")})}) }
TIMEOUT gossiping with peer HcSCitMk46xdzpzna9wfzdKs3dNtiwbf4hUzRGQ3WScbq9bbn3epZTYm43Wzqba
TIMEOUT gossiping with peer HcSCjS58rU9f75hPxhANfiniugzbem4fw3MRCKp3Axj9wz34VE77jMAm5iD78sr
2019-04-11 19:12:40:holo-chat: debug/scheduled_jobs: tick
Strict Fail on Unhandled Promise Rejection
Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.ping (/home/lucksus/code/n3h/node_modules/express-ws/node_modules/ws/lib/websocket.js:249:19)
    at Timeout._pingTimer.setInterval [as _onTimeout] (/home/lucksus/code/n3h/lib/n3h-mod-connection-wss/wss-connection.js:58:14)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
Error occured in p2p network module, on tick: TransportError("Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" }")
2019-04-11 19:12:50:holo-chat: debug/scheduled_jobs: tick
2019-04-11 19:13:00:holo-chat: debug/scheduled_jobs: tick
2019-04-11 19:13:10:holo-chat: debug/scheduled_jobs: tick
2019-04-11 19:13:20:holo-chat: debug/scheduled_jobs: tick
2019-04-11 19:13:30:holo-chat: debug/scheduled_jobs: tick
```

**Comment by lucksus** [comment]
Tried again, from a clean slate only with my two local nodes:
```
TIMEOUT gossiping with peer HcScj4WG4muKBp3v7sQhtz36vZrjvay7xEp8ZIIhsZrrtgac3cSZNedvkx7o8qi
2019-04-11 19:24:35:holo-chat: debug/net/handle: HandleSendMessage: MessageData { dna_address: HashString("QmU7qS2SReM31SfdBuyaGhFCy9mABuenTD3M2TXbiujzFE"), request_id: "puid-2-4", to_agent_id: "HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi", from_agent_id: "HcScIf7MJejaj887bsEA7GOyWWzq3f9diFXGZOcTPigz8irvWCmNUd6eE34f64i", content: Object({"RequestValidationPackage": String("QmXRBNeNZKNu1aqvQdXfw7hErTkJbjZZHhoyJQXr1UXYmo")}) }
2019-04-11 19:24:35:holo-chat: Sending validation package of entry QmXRBNeNZKNu1aqvQdXfw7hErTkJbjZZHhoyJQXr1UXYmo to agent HcScIf7MJejaj887bsEA7GOyWWzq3f9diFXGZOcTPigz8irvWCmNUd6eE34f64i
TIMEOUT gossiping with peer HcScj4WG4muKBp3v7sQhtz36vZrjvay7xEp8ZIIhsZrrtgac3cSZNedvkx7o8qi
Strict Fail on Unhandled Promise Rejection
Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.ping (/home/lucksus/code/n3h/node_modules/express-ws/node_modules/ws/lib/websocket.js:249:19)
    at Timeout._pingTimer.setInterval [as _onTimeout] (/home/lucksus/code/n3h/lib/n3h-mod-connection-wss/wss-connection.js:58:14)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
Error occured in p2p network module, on tick: TransportError("Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" }")
2019-04-11 19:24:40:holo-chat: debug/scheduled_jobs: tick
```

**Comment by lucksus** [comment]
All the above was on my linux workstation which was the bootstrap node for the other nodes.
As seen from my mac who tried connecting, it looked like this:
```
2019-04-11 19:24:30:holo-chat: debug/net/handle: HandleStoreEntry: EntryData { dna_address: HashString("QmU7qS2SReM31SfdBuyaGhFCy9mABuenTD3M2TXbiujzFE"), provider_agent_id: "HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi", entry_address: HashString("QmQ2pmbtAB5ff5p8kf4FZtCdt6e3xJpXJ4an8DZAcrEP4b"), entry_content: Object({"entry": Object({"App": Array([String("chat_profile"), String("{\"name\":\"@lucksus\",\"avatar_url\":\"https://secure.gravatar.com/avatar/10da9a69549eea7d69b9fba48a2367f3\",\"address\":\"HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi\"}")])}), "header": Object({"entry_type": Object({"App": String("chat_profile")}), "entry_address": String("QmQ2pmbtAB5ff5p8kf4FZtCdt6e3xJpXJ4an8DZAcrEP4b"), "provenances": Array([Array([String("HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi"), String("14Z/jBTRzqLYzR17e7qmBHtCfwjmg2TpKK7dAa586GJ2GU+sgIZ5XYzOyV4pDMMuZ57pv40EZZ9AWdo5qjTWBQ==")])]), "link": String("QmXHnF2tCEhfhxqDLHQ2jWubBthPam2VZ1yf58rB8MngcY"), "link_same_type": Null, "link_update_delete": Null, "timestamp": String("2019-04-11T17:24:29+00:00")})}) }
2019-04-11 19:24:30:holo-chat: debug/scheduled_jobs: tick
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
2019-04-11 19:24:35:holo-chat: debug/net/handle: HandleStoreEntry: EntryData { dna_address: HashString("QmU7qS2SReM31SfdBuyaGhFCy9mABuenTD3M2TXbiujzFE"), provider_agent_id: "HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi", entry_address: HashString("QmXRBNeNZKNu1aqvQdXfw7hErTkJbjZZHhoyJQXr1UXYmo"), entry_content: Object({"entry": Object({"LinkAdd": Object({"action_kind": String("ADD"), "link": Object({"base": String("Qmeb26KAiWwoG29VsCARZibdUwchfBD8D771QkJRB41Nxd"), "target": String("HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi"), "tag": String("member_tag")})})}), "header": Object({"entry_type": String("LinkAdd"), "entry_address": String("QmXRBNeNZKNu1aqvQdXfw7hErTkJbjZZHhoyJQXr1UXYmo"), "provenances": Array([Array([String("HcSCj4h6VT5j4Rapb6hq8FIue8Wek89hiWq6J88v4XCmBuvc4bXwHWcEFzt79vi"), String("S8OG04EkcGUhoQUTg8648JFfw1MriltGM7ZnhOOZ+EhVGjKEh42PvWXL5q+BTFJPA0RvFJrNENs60ocl42lVDg==")])]), "link": String("Qme3PH9t1KxjNGTUei7LnQzPwRJfxem1CZJ92LmftxX7Wk"), "link_same_type": Null, "link_update_delete": Null, "timestamp": String("2019-04-11T17:24:29+00:00")})}) }
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
[... MANY OF THESE TIMEOUTS....]
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
2019-04-11 19:25:20:holo-chat: debug/scheduled_jobs: tick
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
{ type: 'conError',
  id: 'wss:out:5.vvdk1i8vry',
  error: 'Error: connect ETIMEDOUT fc55:d888:daac:5ec7:5b16::1:55888\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)' }
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
2019-04-11 19:25:30:holo-chat: debug/scheduled_jobs: tick
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
TIMEOUT gossiping with peer HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi
```

**Comment by lucksus** [comment]
Interestingly, the node HcSCiZFSQonnzx6683CDt6guONVbfwfj7gNhJ5EBcZcin4fsk4hvmVKdOymw6gi that timed out is the linux workstation we just connected to.

**Comment by Connoropolous** [comment]
@lucksus so this is (close to) ready for merge?? Nice work!

There is still a merge conflict though

**Pull request merged**
